#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Wisielec.Resource", IsApplication=true)]

namespace Wisielec
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int Splash = 2130771969;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F020000
			public const int ApplicationName = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int backToMenuButtonLabel = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int enterPlayerName = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int fetchApiInformation = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int informationAboutTakingPrompt = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int newGameLabelButton = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int playAgainButtonLabel = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int rankingLabelButton = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int rankingTitle = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int resultLose = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int resultWin = 2130837514;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F030000
			public const int Theme_Splash = 2130903040;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
